### ISSUE TITLE
[Question] Why users needs RawLineEdit?

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/RawLineEdit#11] opened 2017-02-27 07:23 UTC
### 1. Briefly

I don't understand, why users needs to use RawLineEdit.

### 2. Detail

1. `CR` break type users may see built-in. Example:

![Break-type](https://camo.githubusercontent.com/507ae799bbe68f05d6cf193c0259fe1e5eb4e8be/687474703a2f2f692e696d6775722e636f6d2f476a6b6b7a7a452e706e67)

2. For replacing we can use popular [**EditorConfig plugin**](http://editorconfig.org/). Benefits EditorConfig versus RawLineEdit:

   1. Replacing line ends in all file after save file. It faster than RawLineEdit replacing in each line.
   2. Current color scheme [**don't disable**](https://github.com/facelessuser/RawLineEdit/issues/3).

### 3. Feature request

I would use RawLineEdit, if plugin automatically change CR in unsaved buffers, for example, see [**issue**](https://github.com/Stubbs/sublime-vagrant/issues/33). But RawLineEdit don't have this feature.

Thanks.

**Comment by facelessuser** [comment] 2017-02-27 13:50
> I don't understand, why users needs to use RawLineEdit.

No one **needs** RawLineEdit, but some might find it useful.  If you have no use case for RawLineEdit, then you shouldn't use it.  I personally only write plugins that **I** use, so I had do have specific use cases for it.

Sublime, when saving a file, converts **all** line endings to depending on what line ending setting you have.  Sometimes I want to investigate problems with a file as some files shouldn't have `cr`s.  This tool lets  me open the file and and **confirm** which lines have `cr`s.  That way I can confirm there was a line ending issue with this file instead of blindly converting all and hoping that fixes my issue. There are some file types, if I recall correctly, that allow mixed line endings. This would allow you to view the those files to inspect line endings as editing with Sublime would convert them all.

The editing part isn't really that useful for the way I use it, but if you had a file type that had mixed line endings,  and you only wanted to modify one line ending, you could with this.

> For replacing we can use popular EditorConfig plugin.

Yes they can, and if all they want to do is convert **all** new lines automatically, then they should EditorConfig. 

> Current color scheme don't disable.

Since The purpose of RawLineEdit was to see line endings, not edit code, I wanted to make new lines stand out in "raw line editing" mode.  Syntax isn't important when I am looking at line endings, the line endings are, so I highlight line endings and don't highlight code.  It's the way I use it.

> I would use RawLineEdit, if plugin automatically change CR in unsaved buffers, for example, see issue. But RawLineEdit don't have this feature.

That isn't really within the scope of what I designed RawLineEdit for.  And I honestly think that is a setting for per projects.  Something like EditorConfig would be a better plugin for that sort of behavior.

**Comment by facelessuser** [comment] 2017-04-10 01:01
As the question was essentially answered, and there has been no reply sense February, I will close this issue.

**Closed by facelessuser** 2017-04-10 01:01 UTC
